# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_gc_rcon.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_gc_rcon.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z<github.com/RoboCup-SSL/ssl-game-controller/internal/app/rcon',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11ssl_gc_rcon.proto\"\xa1\x02\n\x0f\x43ontrollerReply\x12\x30\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x1b.ControllerReply.StatusCode\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x12\n\nnext_token\x18\x03 \x01(\t\x12\x33\n\x0cverification\x18\x04 \x01(\x0e\x32\x1d.ControllerReply.Verification\";\n\nStatusCode\x12\x17\n\x13UNKNOWN_STATUS_CODE\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0c\n\x08REJECTED\x10\x02\"F\n\x0cVerification\x12\x18\n\x14UNKNOWN_VERIFICATION\x10\x00\x12\x0c\n\x08VERIFIED\x10\x01\x12\x0e\n\nUNVERIFIED\x10\x02\",\n\tSignature\x12\r\n\x05token\x18\x01 \x02(\t\x12\x10\n\x08pkcs1v15\x18\x02 \x02(\x0c\x42>Z<github.com/RoboCup-SSL/ssl-game-controller/internal/app/rcon'
)



_CONTROLLERREPLY_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='ControllerReply.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_STATUS_CODE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=180,
  serialized_end=239,
)
_sym_db.RegisterEnumDescriptor(_CONTROLLERREPLY_STATUSCODE)

_CONTROLLERREPLY_VERIFICATION = _descriptor.EnumDescriptor(
  name='Verification',
  full_name='ControllerReply.Verification',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_VERIFICATION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERIFIED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNVERIFIED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=241,
  serialized_end=311,
)
_sym_db.RegisterEnumDescriptor(_CONTROLLERREPLY_VERIFICATION)


_CONTROLLERREPLY = _descriptor.Descriptor(
  name='ControllerReply',
  full_name='ControllerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ControllerReply.status_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='ControllerReply.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_token', full_name='ControllerReply.next_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verification', full_name='ControllerReply.verification', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLLERREPLY_STATUSCODE,
    _CONTROLLERREPLY_VERIFICATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=311,
)


_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='Signature.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pkcs1v15', full_name='Signature.pkcs1v15', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=357,
)

_CONTROLLERREPLY.fields_by_name['status_code'].enum_type = _CONTROLLERREPLY_STATUSCODE
_CONTROLLERREPLY.fields_by_name['verification'].enum_type = _CONTROLLERREPLY_VERIFICATION
_CONTROLLERREPLY_STATUSCODE.containing_type = _CONTROLLERREPLY
_CONTROLLERREPLY_VERIFICATION.containing_type = _CONTROLLERREPLY
DESCRIPTOR.message_types_by_name['ControllerReply'] = _CONTROLLERREPLY
DESCRIPTOR.message_types_by_name['Signature'] = _SIGNATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControllerReply = _reflection.GeneratedProtocolMessageType('ControllerReply', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLLERREPLY,
  '__module__' : 'ssl_gc_rcon_pb2'
  # @@protoc_insertion_point(class_scope:ControllerReply)
  })
_sym_db.RegisterMessage(ControllerReply)

Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), {
  'DESCRIPTOR' : _SIGNATURE,
  '__module__' : 'ssl_gc_rcon_pb2'
  # @@protoc_insertion_point(class_scope:Signature)
  })
_sym_db.RegisterMessage(Signature)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
