# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_gc_api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_gc_state_pb2 as ssl__gc__state__pb2
import ssl_gc_change_pb2 as ssl__gc__change__pb2
import ssl_gc_engine_pb2 as ssl__gc__engine__pb2
import ssl_gc_engine_config_pb2 as ssl__gc__engine__config__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_gc_api.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z;github.com/RoboCup-SSL/ssl-game-controller/internal/app/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10ssl_gc_api.proto\x1a\x12ssl_gc_state.proto\x1a\x13ssl_gc_change.proto\x1a\x13ssl_gc_engine.proto\x1a\x1assl_gc_engine_config.proto\x1a\x1egoogle/protobuf/duration.proto\"w\n\x06Output\x12\x1b\n\x0bmatch_state\x18\x01 \x01(\x0b\x32\x06.State\x12\x1a\n\x08gc_state\x18\x02 \x01(\x0b\x32\x08.GcState\x12\x1b\n\x08protocol\x18\x03 \x01(\x0b\x32\t.Protocol\x12\x17\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\x07.Config\"8\n\x08Protocol\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\x08\x12\x1d\n\x05\x65ntry\x18\x02 \x03(\x0b\x32\x0e.ProtocolEntry\"\xa2\x01\n\rProtocolEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x06\x63hange\x18\x02 \x01(\x0b\x32\x07.Change\x12\x35\n\x12match_time_elapsed\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x35\n\x12stage_time_elapsed\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\"~\n\x05Input\x12\x17\n\x06\x63hange\x18\x01 \x01(\x0b\x32\x07.Change\x12\x13\n\x0breset_match\x18\x02 \x01(\x08\x12\x1d\n\x0c\x63onfig_delta\x18\x03 \x01(\x0b\x32\x07.Config\x12(\n\x0f\x63ontinue_action\x18\x04 \x01(\x0b\x32\x0f.ContinueActionB=Z;github.com/RoboCup-SSL/ssl-game-controller/internal/app/api'
  ,
  dependencies=[ssl__gc__state__pb2.DESCRIPTOR,ssl__gc__change__pb2.DESCRIPTOR,ssl__gc__engine__pb2.DESCRIPTOR,ssl__gc__engine__config__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_state', full_name='Output.match_state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gc_state', full_name='Output.gc_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='Output.protocol', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='Output.config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=261,
)


_PROTOCOL = _descriptor.Descriptor(
  name='Protocol',
  full_name='Protocol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='delta', full_name='Protocol.delta', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entry', full_name='Protocol.entry', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=319,
)


_PROTOCOLENTRY = _descriptor.Descriptor(
  name='ProtocolEntry',
  full_name='ProtocolEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtocolEntry.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='change', full_name='ProtocolEntry.change', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='match_time_elapsed', full_name='ProtocolEntry.match_time_elapsed', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stage_time_elapsed', full_name='ProtocolEntry.stage_time_elapsed', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=484,
)


_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='change', full_name='Input.change', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reset_match', full_name='Input.reset_match', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config_delta', full_name='Input.config_delta', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='continue_action', full_name='Input.continue_action', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=612,
)

_OUTPUT.fields_by_name['match_state'].message_type = ssl__gc__state__pb2._STATE
_OUTPUT.fields_by_name['gc_state'].message_type = ssl__gc__engine__pb2._GCSTATE
_OUTPUT.fields_by_name['protocol'].message_type = _PROTOCOL
_OUTPUT.fields_by_name['config'].message_type = ssl__gc__engine__config__pb2._CONFIG
_PROTOCOL.fields_by_name['entry'].message_type = _PROTOCOLENTRY
_PROTOCOLENTRY.fields_by_name['change'].message_type = ssl__gc__change__pb2._CHANGE
_PROTOCOLENTRY.fields_by_name['match_time_elapsed'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_PROTOCOLENTRY.fields_by_name['stage_time_elapsed'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_INPUT.fields_by_name['change'].message_type = ssl__gc__change__pb2._CHANGE
_INPUT.fields_by_name['config_delta'].message_type = ssl__gc__engine__config__pb2._CONFIG
_INPUT.fields_by_name['continue_action'].message_type = ssl__gc__engine__pb2._CONTINUEACTION
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
DESCRIPTOR.message_types_by_name['Protocol'] = _PROTOCOL
DESCRIPTOR.message_types_by_name['ProtocolEntry'] = _PROTOCOLENTRY
DESCRIPTOR.message_types_by_name['Input'] = _INPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT,
  '__module__' : 'ssl_gc_api_pb2'
  # @@protoc_insertion_point(class_scope:Output)
  })
_sym_db.RegisterMessage(Output)

Protocol = _reflection.GeneratedProtocolMessageType('Protocol', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOL,
  '__module__' : 'ssl_gc_api_pb2'
  # @@protoc_insertion_point(class_scope:Protocol)
  })
_sym_db.RegisterMessage(Protocol)

ProtocolEntry = _reflection.GeneratedProtocolMessageType('ProtocolEntry', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOLENTRY,
  '__module__' : 'ssl_gc_api_pb2'
  # @@protoc_insertion_point(class_scope:ProtocolEntry)
  })
_sym_db.RegisterMessage(ProtocolEntry)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'ssl_gc_api_pb2'
  # @@protoc_insertion_point(class_scope:Input)
  })
_sym_db.RegisterMessage(Input)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
