# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_gc_rcon_team.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_gc_rcon_pb2 as ssl__gc__rcon__pb2
import ssl_gc_common_pb2 as ssl__gc__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_gc_rcon_team.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z<github.com/RoboCup-SSL/ssl-game-controller/internal/app/rcon',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16ssl_gc_rcon_team.proto\x1a\x11ssl_gc_rcon.proto\x1a\x13ssl_gc_common.proto\"Y\n\x10TeamRegistration\x12\x11\n\tteam_name\x18\x01 \x02(\t\x12\x1d\n\tsignature\x18\x02 \x01(\x0b\x32\n.Signature\x12\x13\n\x04team\x18\x03 \x01(\x0e\x32\x05.Team\"\xaa\x01\n\x10TeamToController\x12\x1d\n\tsignature\x18\x01 \x01(\x0b\x32\n.Signature\x12\x18\n\x0e\x64\x65sired_keeper\x18\x02 \x01(\x05H\x00\x12,\n\x10\x61\x64vantage_choice\x18\x03 \x01(\x0e\x32\x10.AdvantageChoiceH\x00\x12\x18\n\x0esubstitute_bot\x18\x04 \x01(\x08H\x00\x12\x0e\n\x04ping\x18\x05 \x01(\x08H\x00\x42\x05\n\x03msg\"M\n\x10\x43ontrollerToTeam\x12,\n\x10\x63ontroller_reply\x18\x01 \x01(\x0b\x32\x10.ControllerReplyH\x00\x42\x05\n\x03msgJ\x04\x08\x02\x10\x03*)\n\x0f\x41\x64vantageChoice\x12\x08\n\x04STOP\x10\x00\x12\x0c\n\x08\x43ONTINUE\x10\x01\x42>Z<github.com/RoboCup-SSL/ssl-game-controller/internal/app/rcon'
  ,
  dependencies=[ssl__gc__rcon__pb2.DESCRIPTOR,ssl__gc__common__pb2.DESCRIPTOR,])

_ADVANTAGECHOICE = _descriptor.EnumDescriptor(
  name='AdvantageChoice',
  full_name='AdvantageChoice',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONTINUE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=409,
  serialized_end=450,
)
_sym_db.RegisterEnumDescriptor(_ADVANTAGECHOICE)

AdvantageChoice = enum_type_wrapper.EnumTypeWrapper(_ADVANTAGECHOICE)
STOP = 0
CONTINUE = 1



_TEAMREGISTRATION = _descriptor.Descriptor(
  name='TeamRegistration',
  full_name='TeamRegistration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_name', full_name='TeamRegistration.team_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='TeamRegistration.signature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='team', full_name='TeamRegistration.team', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=155,
)


_TEAMTOCONTROLLER = _descriptor.Descriptor(
  name='TeamToController',
  full_name='TeamToController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='TeamToController.signature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desired_keeper', full_name='TeamToController.desired_keeper', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='advantage_choice', full_name='TeamToController.advantage_choice', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='substitute_bot', full_name='TeamToController.substitute_bot', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ping', full_name='TeamToController.ping', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='TeamToController.msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=158,
  serialized_end=328,
)


_CONTROLLERTOTEAM = _descriptor.Descriptor(
  name='ControllerToTeam',
  full_name='ControllerToTeam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='controller_reply', full_name='ControllerToTeam.controller_reply', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='ControllerToTeam.msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=330,
  serialized_end=407,
)

_TEAMREGISTRATION.fields_by_name['signature'].message_type = ssl__gc__rcon__pb2._SIGNATURE
_TEAMREGISTRATION.fields_by_name['team'].enum_type = ssl__gc__common__pb2._TEAM
_TEAMTOCONTROLLER.fields_by_name['signature'].message_type = ssl__gc__rcon__pb2._SIGNATURE
_TEAMTOCONTROLLER.fields_by_name['advantage_choice'].enum_type = _ADVANTAGECHOICE
_TEAMTOCONTROLLER.oneofs_by_name['msg'].fields.append(
  _TEAMTOCONTROLLER.fields_by_name['desired_keeper'])
_TEAMTOCONTROLLER.fields_by_name['desired_keeper'].containing_oneof = _TEAMTOCONTROLLER.oneofs_by_name['msg']
_TEAMTOCONTROLLER.oneofs_by_name['msg'].fields.append(
  _TEAMTOCONTROLLER.fields_by_name['advantage_choice'])
_TEAMTOCONTROLLER.fields_by_name['advantage_choice'].containing_oneof = _TEAMTOCONTROLLER.oneofs_by_name['msg']
_TEAMTOCONTROLLER.oneofs_by_name['msg'].fields.append(
  _TEAMTOCONTROLLER.fields_by_name['substitute_bot'])
_TEAMTOCONTROLLER.fields_by_name['substitute_bot'].containing_oneof = _TEAMTOCONTROLLER.oneofs_by_name['msg']
_TEAMTOCONTROLLER.oneofs_by_name['msg'].fields.append(
  _TEAMTOCONTROLLER.fields_by_name['ping'])
_TEAMTOCONTROLLER.fields_by_name['ping'].containing_oneof = _TEAMTOCONTROLLER.oneofs_by_name['msg']
_CONTROLLERTOTEAM.fields_by_name['controller_reply'].message_type = ssl__gc__rcon__pb2._CONTROLLERREPLY
_CONTROLLERTOTEAM.oneofs_by_name['msg'].fields.append(
  _CONTROLLERTOTEAM.fields_by_name['controller_reply'])
_CONTROLLERTOTEAM.fields_by_name['controller_reply'].containing_oneof = _CONTROLLERTOTEAM.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['TeamRegistration'] = _TEAMREGISTRATION
DESCRIPTOR.message_types_by_name['TeamToController'] = _TEAMTOCONTROLLER
DESCRIPTOR.message_types_by_name['ControllerToTeam'] = _CONTROLLERTOTEAM
DESCRIPTOR.enum_types_by_name['AdvantageChoice'] = _ADVANTAGECHOICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeamRegistration = _reflection.GeneratedProtocolMessageType('TeamRegistration', (_message.Message,), {
  'DESCRIPTOR' : _TEAMREGISTRATION,
  '__module__' : 'ssl_gc_rcon_team_pb2'
  # @@protoc_insertion_point(class_scope:TeamRegistration)
  })
_sym_db.RegisterMessage(TeamRegistration)

TeamToController = _reflection.GeneratedProtocolMessageType('TeamToController', (_message.Message,), {
  'DESCRIPTOR' : _TEAMTOCONTROLLER,
  '__module__' : 'ssl_gc_rcon_team_pb2'
  # @@protoc_insertion_point(class_scope:TeamToController)
  })
_sym_db.RegisterMessage(TeamToController)

ControllerToTeam = _reflection.GeneratedProtocolMessageType('ControllerToTeam', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLLERTOTEAM,
  '__module__' : 'ssl_gc_rcon_team_pb2'
  # @@protoc_insertion_point(class_scope:ControllerToTeam)
  })
_sym_db.RegisterMessage(ControllerToTeam)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
