# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_autoref_ci.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_vision_wrapper_tracked_pb2 as ssl__vision__wrapper__tracked__pb2
import ssl_vision_detection_pb2 as ssl__vision__detection__pb2
import ssl_vision_geometry_pb2 as ssl__vision__geometry__pb2
import ssl_gc_referee_message_pb2 as ssl__gc__referee__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_autoref_ci.proto',
  package='',
  syntax='proto2',
  serialized_options=b'ZBgithub.com/RoboCup-SSL/ssl-game-controller/internal/app/ci/autoref',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ssl_autoref_ci.proto\x1a ssl_vision_wrapper_tracked.proto\x1a\x1assl_vision_detection.proto\x1a\x19ssl_vision_geometry.proto\x1a\x1cssl_gc_referee_message.proto\"\xb7\x01\n\x0e\x41utoRefCiInput\x12!\n\x0freferee_message\x18\x01 \x01(\x0b\x32\x08.Referee\x12\x35\n\x16tracker_wrapper_packet\x18\x02 \x01(\x0b\x32\x15.TrackerWrapperPacket\x12&\n\tdetection\x18\x03 \x03(\x0b\x32\x13.SSL_DetectionFrame\x12#\n\x08geometry\x18\x04 \x01(\x0b\x32\x11.SSL_GeometryData\"H\n\x0f\x41utoRefCiOutput\x12\x35\n\x16tracker_wrapper_packet\x18\x01 \x01(\x0b\x32\x15.TrackerWrapperPacketBDZBgithub.com/RoboCup-SSL/ssl-game-controller/internal/app/ci/autoref'
  ,
  dependencies=[ssl__vision__wrapper__tracked__pb2.DESCRIPTOR,ssl__vision__detection__pb2.DESCRIPTOR,ssl__vision__geometry__pb2.DESCRIPTOR,ssl__gc__referee__message__pb2.DESCRIPTOR,])




_AUTOREFCIINPUT = _descriptor.Descriptor(
  name='AutoRefCiInput',
  full_name='AutoRefCiInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='referee_message', full_name='AutoRefCiInput.referee_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tracker_wrapper_packet', full_name='AutoRefCiInput.tracker_wrapper_packet', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detection', full_name='AutoRefCiInput.detection', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='AutoRefCiInput.geometry', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=327,
)


_AUTOREFCIOUTPUT = _descriptor.Descriptor(
  name='AutoRefCiOutput',
  full_name='AutoRefCiOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracker_wrapper_packet', full_name='AutoRefCiOutput.tracker_wrapper_packet', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=401,
)

_AUTOREFCIINPUT.fields_by_name['referee_message'].message_type = ssl__gc__referee__message__pb2._REFEREE
_AUTOREFCIINPUT.fields_by_name['tracker_wrapper_packet'].message_type = ssl__vision__wrapper__tracked__pb2._TRACKERWRAPPERPACKET
_AUTOREFCIINPUT.fields_by_name['detection'].message_type = ssl__vision__detection__pb2._SSL_DETECTIONFRAME
_AUTOREFCIINPUT.fields_by_name['geometry'].message_type = ssl__vision__geometry__pb2._SSL_GEOMETRYDATA
_AUTOREFCIOUTPUT.fields_by_name['tracker_wrapper_packet'].message_type = ssl__vision__wrapper__tracked__pb2._TRACKERWRAPPERPACKET
DESCRIPTOR.message_types_by_name['AutoRefCiInput'] = _AUTOREFCIINPUT
DESCRIPTOR.message_types_by_name['AutoRefCiOutput'] = _AUTOREFCIOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AutoRefCiInput = _reflection.GeneratedProtocolMessageType('AutoRefCiInput', (_message.Message,), {
  'DESCRIPTOR' : _AUTOREFCIINPUT,
  '__module__' : 'ssl_autoref_ci_pb2'
  # @@protoc_insertion_point(class_scope:AutoRefCiInput)
  })
_sym_db.RegisterMessage(AutoRefCiInput)

AutoRefCiOutput = _reflection.GeneratedProtocolMessageType('AutoRefCiOutput', (_message.Message,), {
  'DESCRIPTOR' : _AUTOREFCIOUTPUT,
  '__module__' : 'ssl_autoref_ci_pb2'
  # @@protoc_insertion_point(class_scope:AutoRefCiOutput)
  })
_sym_db.RegisterMessage(AutoRefCiOutput)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
