# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_gc_engine_config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_gc_engine_config.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z>github.com/RoboCup-SSL/ssl-game-controller/internal/app/engine',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1assl_gc_engine_config.proto\"\xec\x03\n\x06\x43onfig\x12;\n\x13game_event_behavior\x18\x01 \x03(\x0b\x32\x1e.Config.GameEventBehaviorEntry\x12\x35\n\x10\x61uto_ref_configs\x18\x02 \x03(\x0b\x32\x1b.Config.AutoRefConfigsEntry\x12\x1d\n\x15\x61\x63tive_tracker_source\x18\x03 \x01(\t\x12\r\n\x05teams\x18\x04 \x03(\t\x12\x15\n\rauto_continue\x18\x05 \x01(\x08\x1aJ\n\x16GameEventBehaviorEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0e\x32\x10.Config.Behavior:\x02\x38\x01\x1a\x45\n\x13\x41utoRefConfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.AutoRefConfig:\x02\x38\x01\"\x95\x01\n\x08\x42\x65havior\x12\x14\n\x10\x42\x45HAVIOR_UNKNOWN\x10\x00\x12\x13\n\x0f\x42\x45HAVIOR_ACCEPT\x10\x01\x12\x1c\n\x18\x42\x45HAVIOR_ACCEPT_MAJORITY\x10\x02\x12\x19\n\x15\x42\x45HAVIOR_PROPOSE_ONLY\x10\x03\x12\x10\n\x0c\x42\x45HAVIOR_LOG\x10\x04\x12\x13\n\x0f\x42\x45HAVIOR_IGNORE\x10\x05\"\x84\x02\n\rAutoRefConfig\x12\x42\n\x13game_event_behavior\x18\x01 \x03(\x0b\x32%.AutoRefConfig.GameEventBehaviorEntry\x1aQ\n\x16GameEventBehaviorEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0e\x32\x17.AutoRefConfig.Behavior:\x02\x38\x01\"\\\n\x08\x42\x65havior\x12\x14\n\x10\x42\x45HAVIOR_UNKNOWN\x10\x00\x12\x13\n\x0f\x42\x45HAVIOR_ACCEPT\x10\x01\x12\x10\n\x0c\x42\x45HAVIOR_LOG\x10\x02\x12\x13\n\x0f\x42\x45HAVIOR_IGNORE\x10\x03\x42@Z>github.com/RoboCup-SSL/ssl-game-controller/internal/app/engine'
)



_CONFIG_BEHAVIOR = _descriptor.EnumDescriptor(
  name='Behavior',
  full_name='Config.Behavior',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_ACCEPT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_ACCEPT_MAJORITY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_PROPOSE_ONLY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_LOG', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_IGNORE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=374,
  serialized_end=523,
)
_sym_db.RegisterEnumDescriptor(_CONFIG_BEHAVIOR)

_AUTOREFCONFIG_BEHAVIOR = _descriptor.EnumDescriptor(
  name='Behavior',
  full_name='AutoRefConfig.Behavior',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_ACCEPT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_LOG', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEHAVIOR_IGNORE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=694,
  serialized_end=786,
)
_sym_db.RegisterEnumDescriptor(_AUTOREFCONFIG_BEHAVIOR)


_CONFIG_GAMEEVENTBEHAVIORENTRY = _descriptor.Descriptor(
  name='GameEventBehaviorEntry',
  full_name='Config.GameEventBehaviorEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Config.GameEventBehaviorEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Config.GameEventBehaviorEntry.value', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=300,
)

_CONFIG_AUTOREFCONFIGSENTRY = _descriptor.Descriptor(
  name='AutoRefConfigsEntry',
  full_name='Config.AutoRefConfigsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Config.AutoRefConfigsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Config.AutoRefConfigsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=371,
)

_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_event_behavior', full_name='Config.game_event_behavior', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auto_ref_configs', full_name='Config.auto_ref_configs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active_tracker_source', full_name='Config.active_tracker_source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='teams', full_name='Config.teams', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auto_continue', full_name='Config.auto_continue', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONFIG_GAMEEVENTBEHAVIORENTRY, _CONFIG_AUTOREFCONFIGSENTRY, ],
  enum_types=[
    _CONFIG_BEHAVIOR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=523,
)


_AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY = _descriptor.Descriptor(
  name='GameEventBehaviorEntry',
  full_name='AutoRefConfig.GameEventBehaviorEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AutoRefConfig.GameEventBehaviorEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='AutoRefConfig.GameEventBehaviorEntry.value', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=692,
)

_AUTOREFCONFIG = _descriptor.Descriptor(
  name='AutoRefConfig',
  full_name='AutoRefConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_event_behavior', full_name='AutoRefConfig.game_event_behavior', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY, ],
  enum_types=[
    _AUTOREFCONFIG_BEHAVIOR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=786,
)

_CONFIG_GAMEEVENTBEHAVIORENTRY.fields_by_name['value'].enum_type = _CONFIG_BEHAVIOR
_CONFIG_GAMEEVENTBEHAVIORENTRY.containing_type = _CONFIG
_CONFIG_AUTOREFCONFIGSENTRY.fields_by_name['value'].message_type = _AUTOREFCONFIG
_CONFIG_AUTOREFCONFIGSENTRY.containing_type = _CONFIG
_CONFIG.fields_by_name['game_event_behavior'].message_type = _CONFIG_GAMEEVENTBEHAVIORENTRY
_CONFIG.fields_by_name['auto_ref_configs'].message_type = _CONFIG_AUTOREFCONFIGSENTRY
_CONFIG_BEHAVIOR.containing_type = _CONFIG
_AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY.fields_by_name['value'].enum_type = _AUTOREFCONFIG_BEHAVIOR
_AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY.containing_type = _AUTOREFCONFIG
_AUTOREFCONFIG.fields_by_name['game_event_behavior'].message_type = _AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY
_AUTOREFCONFIG_BEHAVIOR.containing_type = _AUTOREFCONFIG
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['AutoRefConfig'] = _AUTOREFCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {

  'GameEventBehaviorEntry' : _reflection.GeneratedProtocolMessageType('GameEventBehaviorEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONFIG_GAMEEVENTBEHAVIORENTRY,
    '__module__' : 'ssl_gc_engine_config_pb2'
    # @@protoc_insertion_point(class_scope:Config.GameEventBehaviorEntry)
    })
  ,

  'AutoRefConfigsEntry' : _reflection.GeneratedProtocolMessageType('AutoRefConfigsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONFIG_AUTOREFCONFIGSENTRY,
    '__module__' : 'ssl_gc_engine_config_pb2'
    # @@protoc_insertion_point(class_scope:Config.AutoRefConfigsEntry)
    })
  ,
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'ssl_gc_engine_config_pb2'
  # @@protoc_insertion_point(class_scope:Config)
  })
_sym_db.RegisterMessage(Config)
_sym_db.RegisterMessage(Config.GameEventBehaviorEntry)
_sym_db.RegisterMessage(Config.AutoRefConfigsEntry)

AutoRefConfig = _reflection.GeneratedProtocolMessageType('AutoRefConfig', (_message.Message,), {

  'GameEventBehaviorEntry' : _reflection.GeneratedProtocolMessageType('GameEventBehaviorEntry', (_message.Message,), {
    'DESCRIPTOR' : _AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY,
    '__module__' : 'ssl_gc_engine_config_pb2'
    # @@protoc_insertion_point(class_scope:AutoRefConfig.GameEventBehaviorEntry)
    })
  ,
  'DESCRIPTOR' : _AUTOREFCONFIG,
  '__module__' : 'ssl_gc_engine_config_pb2'
  # @@protoc_insertion_point(class_scope:AutoRefConfig)
  })
_sym_db.RegisterMessage(AutoRefConfig)
_sym_db.RegisterMessage(AutoRefConfig.GameEventBehaviorEntry)


DESCRIPTOR._options = None
_CONFIG_GAMEEVENTBEHAVIORENTRY._options = None
_CONFIG_AUTOREFCONFIGSENTRY._options = None
_AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY._options = None
# @@protoc_insertion_point(module_scope)
