# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_gc_ci.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_vision_wrapper_tracked_pb2 as ssl__vision__wrapper__tracked__pb2
import ssl_gc_api_pb2 as ssl__gc__api__pb2
import ssl_gc_referee_message_pb2 as ssl__gc__referee__message__pb2
import ssl_vision_geometry_pb2 as ssl__vision__geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_gc_ci.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z:github.com/RoboCup-SSL/ssl-game-controller/internal/app/ci',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fssl_gc_ci.proto\x1a ssl_vision_wrapper_tracked.proto\x1a\x10ssl_gc_api.proto\x1a\x1cssl_gc_referee_message.proto\x1a\x19ssl_vision_geometry.proto\"\x8c\x01\n\x07\x43iInput\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12-\n\x0etracker_packet\x18\x02 \x01(\x0b\x32\x15.TrackerWrapperPacket\x12\x1a\n\napi_inputs\x18\x03 \x03(\x0b\x32\x06.Input\x12#\n\x08geometry\x18\x04 \x01(\x0b\x32\x11.SSL_GeometryData\")\n\x08\x43iOutput\x12\x1d\n\x0breferee_msg\x18\x01 \x01(\x0b\x32\x08.RefereeB<Z:github.com/RoboCup-SSL/ssl-game-controller/internal/app/ci'
  ,
  dependencies=[ssl__vision__wrapper__tracked__pb2.DESCRIPTOR,ssl__gc__api__pb2.DESCRIPTOR,ssl__gc__referee__message__pb2.DESCRIPTOR,ssl__vision__geometry__pb2.DESCRIPTOR,])




_CIINPUT = _descriptor.Descriptor(
  name='CiInput',
  full_name='CiInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CiInput.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tracker_packet', full_name='CiInput.tracker_packet', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_inputs', full_name='CiInput.api_inputs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='CiInput.geometry', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=269,
)


_CIOUTPUT = _descriptor.Descriptor(
  name='CiOutput',
  full_name='CiOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='referee_msg', full_name='CiOutput.referee_msg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=312,
)

_CIINPUT.fields_by_name['tracker_packet'].message_type = ssl__vision__wrapper__tracked__pb2._TRACKERWRAPPERPACKET
_CIINPUT.fields_by_name['api_inputs'].message_type = ssl__gc__api__pb2._INPUT
_CIINPUT.fields_by_name['geometry'].message_type = ssl__vision__geometry__pb2._SSL_GEOMETRYDATA
_CIOUTPUT.fields_by_name['referee_msg'].message_type = ssl__gc__referee__message__pb2._REFEREE
DESCRIPTOR.message_types_by_name['CiInput'] = _CIINPUT
DESCRIPTOR.message_types_by_name['CiOutput'] = _CIOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CiInput = _reflection.GeneratedProtocolMessageType('CiInput', (_message.Message,), {
  'DESCRIPTOR' : _CIINPUT,
  '__module__' : 'ssl_gc_ci_pb2'
  # @@protoc_insertion_point(class_scope:CiInput)
  })
_sym_db.RegisterMessage(CiInput)

CiOutput = _reflection.GeneratedProtocolMessageType('CiOutput', (_message.Message,), {
  'DESCRIPTOR' : _CIOUTPUT,
  '__module__' : 'ssl_gc_ci_pb2'
  # @@protoc_insertion_point(class_scope:CiOutput)
  })
_sym_db.RegisterMessage(CiOutput)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
